# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autotransition.ui'
#
# Created: Sat Aug 01 18:18:22 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 400)
        MainWindow.setMinimumSize(QtCore.QSize(600, 400))
        MainWindow.setBaseSize(QtCore.QSize(600, 400))
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/MetroUI-Folder-OS-Ubuntu-Alt-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDocumentMode(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lcd_sum = QtGui.QLCDNumber(self.centralwidget)
        self.lcd_sum.setEnabled(True)
        self.lcd_sum.setMinimumSize(QtCore.QSize(0, 40))
        self.lcd_sum.setStyleSheet("")
        self.lcd_sum.setSmallDecimalPoint(False)
        self.lcd_sum.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_sum.setObjectName("lcd_sum")
        self.gridLayout_2.addWidget(self.lcd_sum, 0, 0, 1, 1)
        self.lcd_me = QtGui.QLCDNumber(self.centralwidget)
        self.lcd_me.setMinimumSize(QtCore.QSize(0, 40))
        self.lcd_me.setStyleSheet("color: rgb(0, 255, 127);")
        self.lcd_me.setObjectName("lcd_me")
        self.gridLayout_2.addWidget(self.lcd_me, 0, 1, 1, 1)
        self.lcd_check = QtGui.QLCDNumber(self.centralwidget)
        self.lcd_check.setMinimumSize(QtCore.QSize(0, 40))
        self.lcd_check.setStyleSheet("color: rgb(212, 212, 0);")
        self.lcd_check.setObjectName("lcd_check")
        self.gridLayout_2.addWidget(self.lcd_check, 0, 2, 1, 1)
        self.lcd_error = QtGui.QLCDNumber(self.centralwidget)
        self.lcd_error.setMinimumSize(QtCore.QSize(0, 40))
        self.lcd_error.setStyleSheet("color: rgb(194, 0, 0);")
        self.lcd_error.setObjectName("lcd_error")
        self.gridLayout_2.addWidget(self.lcd_error, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 57, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 2, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 3, 0, 2, 4)
        spacerItem1 = QtGui.QSpacerItem(20, 67, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 4, 2, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 5, 0, 1, 1)
        self.button_open = QtGui.QPushButton(self.centralwidget)
        self.button_open.setEnabled(True)
        self.button_open.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button_open.setFont(font)
        self.button_open.setAutoFillBackground(False)
        self.button_open.setStyleSheet("")
        self.button_open.setIconSize(QtCore.QSize(32, 32))
        self.button_open.setCheckable(False)
        self.button_open.setChecked(False)
        self.button_open.setAutoDefault(False)
        self.button_open.setDefault(False)
        self.button_open.setFlat(False)
        self.button_open.setObjectName("button_open")
        self.gridLayout_2.addWidget(self.button_open, 5, 2, 1, 1)
        self.button_start = QtGui.QPushButton(self.centralwidget)
        self.button_start.setEnabled(True)
        self.button_start.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button_start.setFont(font)
        self.button_start.setStyleSheet("")
        self.button_start.setIcon(icon)
        self.button_start.setIconSize(QtCore.QSize(32, 32))
        self.button_start.setCheckable(False)
        self.button_start.setAutoDefault(False)
        self.button_start.setDefault(False)
        self.button_start.setFlat(False)
        self.button_start.setObjectName("button_start")
        self.gridLayout_2.addWidget(self.button_start, 5, 3, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 6, 0, 1, 4)
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setAcceptDrops(False)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser.setDocumentTitle("")
        self.textBrowser.setReadOnly(True)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 7, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setStyleSheet("")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setCheckable(False)
        self.actionExit.setObjectName("actionExit")
        self.actionAbou_Me = QtGui.QAction(MainWindow)
        self.actionAbou_Me.setCheckable(False)
        self.actionAbou_Me.setObjectName("actionAbou_Me")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbou_Me)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Customs Handfree V. 1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">Sum</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">Me</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">Checked</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">Error</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Infomation :", None, QtGui.QApplication.UnicodeUTF8))
        self.button_open.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.button_start.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbou_Me.setText(QtGui.QApplication.translate("MainWindow", "Abou Me", None, QtGui.QApplication.UnicodeUTF8))

import picture_rc
